# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Story_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_dirname', models.CharField(max_length=50)),
                ('content_path', models.CharField(max_length=50, null=True)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Story')),
            ],
            options={
                'db_table': 'story_text',
            },
        ),
    ]
