# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191021_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_text',
            name='story',
            field=models.ForeignKey(db_column='story123', on_delete=django.db.models.deletion.CASCADE, to='index.Story'),
        ),
    ]
