# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191021_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='story_text',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Story'),
        ),
    ]
