# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191023_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='images',
            field=models.ImageField(null=True, upload_to='static/upload/'),
        ),
    ]
