# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191024_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='static/upload/')),
            ],
            options={
                'db_table': 'UserImages',
            },
        ),
        migrations.RemoveField(
            model_name='topic',
            name='images',
        ),
        migrations.AddField(
            model_name='userimages',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Topic'),
        ),
    ]
