# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-24 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191024_1621'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userimages',
            table='userImages',
        ),
    ]
