# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191024_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
