# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
